#!/bin/bash
cp mac/bundle-mac zed/script && cp mac/config.toml zed/.cargo/config.toml && cp mac/Cargo.toml zed/Cargo.toml
cd zed
set -eu
cross build -p remote_server --target x86_64-unknown-linux-gnu --release
# cross build --package remote_server --target aarch64-unknown-linux-gnu --release
# cargo build --package remote_server --target x86_64-unknown-linux-gnu --release
