#!/bin/bash

# 检查并创建必要的目标目录
if [ ! -d "target" ]; then
    mkdir -p "target"
    echo "创建 target 目录..."
fi

# 创建DMG函数
create_dmg() {
    local arch=$1
    local timestr=$(date "+%y%m%d")
    local target_dir="zed/target/$arch/zed"
    local dmg_path="target/zed-$arch-$timestr.dmg"
    local app_path="zed/target/${arch}/release/bundle/osx/Zed.app"
    local cli_path="zed/target/${arch}/release/cli"
    echo "创建 $arch 架构的DMG..."
    rm -rf $target_dir && mkdir -p $target_dir # 清理并重建目录
    cp ${cli_path} ${app_path}/Contents/MacOS/cli  #复制cli
    cp -R ${app_path} "$target_dir/Zed.app"  # 复制应用
    ln -s /Applications $target_dir # 可选：添加快捷方式
    # 创建DMG
    hdiutil create -volname "zed_cn" -srcfolder $target_dir -ov -format UDZO $dmg_path

}
copydmg(){
    local arch=$1
    local timestr=$(date "+%y%m%d")
    local dmg_name="zed-$arch-$timestr.dmg"

    echo "复制 $arch 架构的DMG..."
    # 复制 DMG 到目标目录
    cp "zed/target/$arch/release/Zed.dmg" "target/$dmg_name"
    if [ $? -ne 0 ]; then
        echo "复制 DMG 失败"
        return 1
    fi
    echo "复制 $arch 架构的DMG 完成"
    return 0


}
# 为两种架构创建DMG
# copydmg "aarch64-apple-darwin"
copydmg "x86_64-apple-darwin"
echo "所有架构的DMG创建完成"
