[build]
# v0 mangling scheme provides more detailed backtraces around closures
rustflags = ["-C", "symbol-mangling-version=v0", "--cfg", "tokio_unstable"]

[alias]
xtask = "run --package xtask --"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "-C", "link-arg=-fuse-ld=mold",
    "-C", "linker-plugin-lto",
    "-C", "opt-level=z",
    "-C", "strip=symbols",
    "-C", "panic=abort",
    "-C", "strip=debuginfo"
]

[target.aarch64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "-C", "link-arg=-fuse-ld=mold",
    "-C", "linker-plugin-lto",
    "-C", "opt-level=z",
    "-C", "strip=symbols",
    "-C", "panic=abort",
    "-C", "strip=debuginfo"
]

[env]
MACOSX_DEPLOYMENT_TARGET = "10.15.7"
