name: 删除无用词条并提交
on:
  workflow_dispatch:

jobs:
  delete:
    name: 删除
    runs-on: ubuntu-latest
    env:
      LANG: zh_CN.UTF-8

    steps:
      - name: 拉取
        uses: actions/checkout@v4

      - name: GA 终端中文显示
        run: |
          sudo apt-get update
          sudo apt-get install language-pack-zh-hans

      - name: 设置 Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: 自动删除
        run: python3 delete.py

      - name: 提交并推送
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add ./string.json
          git commit -m 'GA：删除多余词条'
          git push
