name: Build Remote Server (Linux)

on:
  workflow_dispatch: # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 手动同步 zed 源代码
        uses: actions/checkout@v4
        with:
          repository: zed-industries/zed
          ref: main
          path: zed

      - name: Install Rust
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: 安装 Linux 依赖项
        run: |
          cp mac/github-config.toml zed/.cargo/config.toml && cp mac/Cargo.toml zed/Cargo.toml
          ./zed/script/linux
          ./zed/script/install-mold 2.34.0
          ./zed/script/clear-target-dir-if-larger-than 100

      - name: Build Remote Server
        run: cd zed && cargo build -p remote_server --release 

      - name: Create tarball
        run: |
          mkdir -p package
          cp zed/target/release/remote_server package/
          tar czvf remote_server-linux.tar.gz package/*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: remote_server-linux
          path: remote_server-linux.tar.gz

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: remote-server-linux-${{ github.run_id }}
          release_name: Remote Server Linux Build ${{ github.run_id }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./remote_server-linux.tar.gz
          asset_name: remote_server-linux.tar.gz
          asset_content_type: application/gzip