name: 词条提取
on:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  extract:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: 设置 Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: 手动同步 zed 源代码
        uses: actions/checkout@v4
        with:
          repository: zed-industries/zed
          ref: main
          path: zed
      - name: 提取
        run: python3 extract.py
      - name: 上传词条文件
        uses: actions/upload-artifact@v4
        with:
          path: string.json
