name: Linux 编译

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: 设置 Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - uses: actions/checkout@v4
      - name: 手动同步 zed 源代码
        uses: actions/checkout@v4
        with:
          repository: zed-industries/zed
          ref: main
          path: zed
      - name: 替换
        run: python3 replace.py

      - name: 将 Rust 添加到 PATH
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: 安装 Linux 依赖项
        run: ./zed/script/linux && ./zed/script/install-mold 2.34.0

      - name: 限制目标目录大小
        run: zed/script/clear-target-dir-if-larger-than 100

      - name: 创建 Linux .tar.gz 包
        run: cd zed && script/bundle-linux

      - name: 找到匹配文件
        id: find_files
        run: echo "matches=$(find zed/target -name 'zed-*-linux-x86_64.tar.gz')" >> $GITHUB_ENV

      - name: 上传文件
        uses: actions/upload-artifact@v4
        with:
          name: zed-linux-x86_64
          path: ${{ env.matches }}
