name: MacOS 编译

on:
  push:
    branches:
      - main
      - "v[0-9]+.[0-9]+.x"
  workflow_dispatch:
    inputs:
      branch:
        type: string
        default: main
        description: "分支名"
env:
    CARGO_TERM_COLOR: always
    CARGO_INCREMENTAL: 0
    RUST_BACKTRACE: 1

jobs:
  bundle-mac:
    timeout-minutes: 60
    name: macOS 编译
    runs-on: macos-latest
    strategy:
      matrix:
        target: [x86_64-apple-darwin, aarch64-apple-darwin]
    steps:
      - uses: actions/setup-rust@v1
        with:
          toolchain: stable
      - name: Install Soft
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: "18"
      - uses: actions/setup-xcode@v3 # 安装指定Xcode版本
        with:
          xcode-version: "14.3" # 指定版本（如beta版可写'beta'）
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          
      - uses: actions/checkout@v4
      - name: 手动同步 zed 源代码
        uses: actions/checkout@v4
        with:
          repository: zed-industries/zed
          ref: main
          path: zed

      - name: replace
        run: |
          python3 replace.py

      - name: Create macOS app bundle
        run: |
          cd zed
          script/clear-target-dir-if-larger-than 100
          script/bundle-mac
          ls -an
          cd target && ls -an
