name: MacOS 编译
on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        default: main
        description: "分支名"

jobs:
  bundle-mac:
    timeout-minutes: 60
    name: macOS 编译
    runs-on: macos-latest
    env:
      CARGO_TERM_COLOR: always
      CARGO_INCREMENTAL: 0
      RUST_BACKTRACE: 1
      # 关键修复 - 强制使用 C++17 标准
      CXXFLAGS: "-std=c++17 -D_LIBCPP_DISABLE_NODISCARD_EXT"
      MACOSX_DEPLOYMENT_TARGET: "10.15"
    steps:
      - name: Install Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: "18"

      - name: 设置 Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          
      - uses: actions/checkout@v4
        
      - name: 手动同步 zed 源代码
        uses: actions/checkout@v4
        with:
          repository: zed-industries/zed
          ref: ${{ inputs.branch }}
          path: zed

      - name: 替换
        run: python3 replace.py

      - name: Xcode
        run: |
          sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
          sudo xcodebuild -license accept          

      - name: 编译
        run: |  
          cd zed
          # 确保使用正确的编译器
          export CC=/usr/bin/clang
          export CXX=/usr/bin/clang++
          
          # 更新依赖并安装必要工具
          cargo update -p webrtc-sys
          cargo install cargo-about@^0.7
          
          # 执行编译
          script/bundle-mac

      - name: Upload Zed Nightly
        run: cd zed && script/upload-nightly macos