name: MacOS build
on:
  push:
    branches:
      - main
      - "v[0-9]+.[0-9]+.x"
  workflow_dispatch:
    inputs:
      branch:
        type: string
        default: main
        description: "分支名"

jobs:
  bundle-mac:
    timeout-minutes: 60
    name: macOS build
    runs-on: macos-13
    env:
      CARGO_TERM_COLOR: always
      CARGO_INCREMENTAL: 0
      RUST_BACKTRACE: 1
    steps:
      - name: Display environment information
        run: |
          uname -m
          xcodebuild -version
          rustc --version
          cargo --version
          jq --version
          rustup toolchain list
          export BINDGEN_EXTRA_CLANG_ARGS="--sysroot=$(xcrun --show-sdk-path)"

      - name: Install cargo-about
        run: cargo install cargo-about && brew install cmake

      - name: Install Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: "18"

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - uses: actions/checkout@v4
      - name: sync zed source code
        uses: actions/checkout@v4
        with:
          repository: zed-industries/zed
          ref: main
          path: zed

      - name: replace language chinese
        run: python3 replace.py

      - name: Xcode
        run: |
          sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
          sudo xcodebuild -license accept
      # - name: Cmake
      #   run: brew install cmake

      - name: Set release channel to stable
        run: |
          cd zed
          set -eu
          version=$(git rev-parse --short HEAD)
          echo "Publishing version: ${version} on release channel stable"
          echo "stable" > crates/zed/RELEASE_CHANNEL

      - name: build
        run: |
          cd zed
          script/bundle-mac

      - name: Move files
        run: move macos

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: |
            Zed-aarch64.dmg
            Zed-x86_64.dmg
            zed-remote-server-*.gz
