name: MacOS 编译
on: 
  push:
    branches:
      - main
      - "v[0-9]+.[0-9]+.x"
  workflow_dispatch:
    inputs:
      branch:
        type: string
        default: main
        description: "分支名"

jobs:
  bundle-mac:
    timeout-minutes: 60
    name: macOS 编译
    runs-on: macos-latest
    env:
      CARGO_TERM_COLOR: always
      CARGO_INCREMENTAL: 0
      RUST_BACKTRACE: 1
    steps:
      - name: Install Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: "18"

      - name: 设置 Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: 手动同步 zed 源代码
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          repository: zed-industries/zed
          ref:  main
          path: zed

      - name: Limit target directory size
        run: |
          python3 replace.py
          mv ./zed/* ./
          script/clear-target-dir-if-larger-than 100

      - name: Create macOS app bundle
        run: |
          ls -an 
          script/bundle-mac
          ls -an 
          cd target && ls -an
        